### ISSUE TITLE
[Maintenance] Add an email server for administrator notifications

### ISSUE THREAD

**Issue by MartinX3** [MartinX3-AdministrativeDevelopment/ServerContainerTemplate#15]
https://dovecot.org/
https://hub.docker.com/r/dovecot/dovecot

Mailu.io

https://github.com/docker-mailserver/docker-mailserver

rootless SMTP -> https://github.com/haraka/Haraka
LDAP plugin
https://github.com/haraka/Haraka/blob/master/Plugins.md
https://github.com/haraka/haraka-plugin-auth-ldap
Dockerimage
https://github.com/instrumentisto/haraka-docker-image

**Comment by Loader009** [comment]
Mailu.io seems to be old with outdated configs - dunno how good it is
alternative:
https://mailcow.email/
https://mailcow.github.io/mailcow-dockerized-docs/prerequisite-system/
But high resource usage.

**Comment by Loader009** [comment]
postfix for SMTP
https://registry.hub.docker.com/r/juanluisbaptiste/postfix
