### ISSUE TITLE
[Podman] network-alias on multiple networks doesn't work

### ISSUE THREAD

**Issue by Loader009** [MartinX3-AdministrativeDevelopment/ServerContainerTemplate#46]
--network-alias=alias

[…]NOTE: A container will only have access to aliases on the first network that it joins. This is a limitation that will be removed in a later release.

https://docs.podman.io/en/latest/markdown/podman-pod-create.1.html#network-alias-alias

https://github.com/containers/dnsname/issues/12#issuecomment-1020170314

**Comment by MartinX3** [comment]
Will be fixed starting from Podman 4.0
https://github.com/containers/podman/issues/13053#issuecomment-1024018972

**Comment by Loader009** [comment]
> Will be fixed starting from Podman 4.0 [containers/podman#13053 (comment)](https://github.com/containers/podman/issues/13053#issuecomment-1024018972)

You're wrong, only IP options for several networks will be fixed according to that issue.

**Comment by Loader009** [comment]
workaround:
use `--add-host=host:ip` parameter - multiple parameters allowed.
It adds the host to /etc/hosts.

**Comment by MartinX3** [comment]
Should be fixed with 4.0
